services:
  postgres:
    image: postgres:16-alpine
    container_name: lcczero-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: lccuser
      POSTGRES_PASSWORD: lccpass
      POSTGRES_DB: lccdb
    volumes:
      - lcczero-pgdata:/var/lib/postgresql/data

volumes:
  lcczero-pgdata:
